project_id = "zfpgprlzpuovavxeiqnr"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.chatgpt-solution]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-user-credits]
verify_jwt = true

[functions.use-credit]
verify_jwt = true