// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfpgprlzpuovavxeiqnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmcGdwcmx6cHVvdmF2eGVpcW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjE4MjQsImV4cCI6MjA3MjQ5NzgyNH0.TN6XF7Z9GhcgYA9iMHjWdjxq3Z0zSuZdbzkj17oo0Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});